#cluster_slurm.yaml for unmap_and_subtract_mouse.snakefile
#Anna-Lisa Doebley
#Template made 2020-04-27
#Ha Lab
#Fred Hutchinson Cancer Research Center

__default__:
    partition: campus-new
    time: "24:0:0"
    mem: 4G
    ncpus: 1
    ntasks: 1
    output: logs/cluster/{rule}.{wildcards.samples}.%A.out
    JobName: "{rule}.{wildcards.samples}.%A"

unmap:
    partition: campus-new
    mem: 72G
    ncpus: 6
    time: "72:0:0"

map_to_ConcatRef:
    time: "48:0:0"
    mem: 12G
    ncpus: 4

sort_concatRef_by_coord:
    mem: 8G

###
unmap_cleaned:
    partition: campus-new
    mem: 72G
    ncpus: 6
    time: "72:0:0"

map_to_human_ref:
    time: "48:0:0"
    mem: 12G
    ncpus: 4

sort_by_coord_cleaned:
    mem: 8G

mark_dups_cleaned:
    partition: campus-new
    mem: 72G
    ncpus: 6

build_recalibrator_model_cleaned:
    mem: 8G

apply_recalibration_cleaned:
    time: "48:0:0"
    mem: 8G

rename_index_files_cleaned:
    time: "1:0:0"

