#config.yaml for unmap_and_subtract_mouse.snakefile and realign_bam_paired.snakefile
#Anna-Lisa Doebley
#Ha Lab
#Fred Hutchinson Cancer Research Center

#SELECT CORRECT REFERENCE GENOME
#reference genome for alignment, with index files in same folder as .fa file
reference_genome:
    /fh/fast/ha_g/grp/reference/GRCh38/Broad_bundle_hg38/v0/Homo_sapiens_assembly38.fasta #human reference genome
ConcatRef_genome:
    /fh/fast/ha_g/grp/reference/ConcatRef/fasta/GRCh38_plus_UCSC_mm10_Broad.fa #ConcatRef created by concatenate_reference.py

tag: UCSC_mm10 #make sure to use the same tag info of ConcatRef

#SELECT CORRECT POLYMORPHIC SITES
known_polymorphic_sites1:
    /fh/fast/ha_g/grp/reference/GRCh38/known_polymorphic_sites/dbsnp_151_hg38_with_chr.All_20180418.vcf.gz
    #/fh/fast/ha_g/grp/reference/GRCh37/known_polymorphic_sites/dbsnp_151_hg19_with_chr.All_20180423.vcf.gz
known_polymorphic_sites2:
    /fh/fast/ha_g/grp/reference/GRCh38/known_polymorphic_sites/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
    #/fh/fast/ha_g/grp/reference/GRCh37/known_polymorphic_sites/Mills_and_1000G_gold_standard.indels.b37.vcf.gz

#SELECT IF DATA IS WHOLE GENOME SEQUENCES OR NOT (True or False)
#determines if rule get_wgs_metrics is run
is_wgs: True

#SELECT CORRECT BASE RECALIBRATOR GAP OPEN PENALTY
#GATK recommends 40 for exomes and 30 for whole genomes
base_recalibrator_gap_open_penalty: 30.0

#can adjust the number of threads used for bwa based on the data
#suggested this matches cluster_slurm.yaml ncpus for map_to_reference rule
bwa_threads: 4

#tools used.  need to be module loaded first.  see snakemake file for loads
bwa: /app/software/BWA/0.7.17-foss-2018b/bin/bwa
samtools: /app/software/SAMtools/1.10-GCCcore-8.3.0/bin/samtools
java: /app/software/Java/1.8.0_181/bin/java
gatk: /app/software/GATK/4.1.0.0-foss-2018b-Python-3.6.6/gatk
picard_jar: $EBROOTPICARD/picard.jar
