#config.yaml for subtract_mouse_and_realign.snakefile
#Anna-Lisa Doebley
#Template made 2021-09-24
#Ha Lab
#Fred Hutchinson Cancer Research Center

#SELECT CORRECT REFERENCE GENOME
#if the input is a cram file, specify the reference gnenome
input_reference_genome: /fh/fast/ha_g/grp/reference/GRCh38/Broad_bundle_hg38/v0/Homo_sapiens_assembly38.fasta
#input_reference_genome: 'null' #for bam file input

#location of the concatref genome for mouse subtraction
ConcatRef_genome:
    /fh/fast/ha_g/grp/reference/ConcatRef/fasta/GRCh38_plus_UCSC_mm10_Broad.fa #ConcatRef created by concatenate_reference.py
    #/fh/fast/ha_g/grp/reference/ConcatRef/fasta/GRCh38_plus_NCBI_GRCm38.fa #option used by Anna-Lisa in her projects

#reference genome for realignment, with index files in same folder as .fa file
human_reference_genome:
    /fh/fast/ha_g/grp/reference/GRCh38/Broad_bundle_hg38/v0/Homo_sapiens_assembly38.fasta #human reference genome
    #/fh/fast/ha_g/grp/reference/GRCh38/GRCh38.fa #option used by Anna-Lisa in her projects

tag: UCSC_mm10  #make sure to use the same tag info of ConcatRef
    #NCBI_GRCm38 #option used by Anna-Lisa in her projects

#specify a path for the logs and results
results_path: results

#SELECT CORRECT POLYMORPHIC SITES
known_polymorphic_sites1:
    /fh/fast/ha_g/grp/reference/GRCh38/known_polymorphic_sites/dbsnp_151_hg38_with_chr.All_20180418.vcf.gz

known_polymorphic_sites2:
    /fh/fast/ha_g/grp/reference/GRCh38/known_polymorphic_sites/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz

#SELECT IF DATA IS WHOLE GENOME SEQUENCES OR NOT (True or False)
#determines if rule get_wgs_metrics is run
is_wgs: True

#SELECT CORRECT BASE RECALIBRATOR GAP OPEN PENALTY
#GATK recommends 40 for exomes and 30 for whole genomes
base_recalibrator_gap_open_penalty: 30.0

#can adjust the number of threads used for bwa based on the data
#suggested this matches cluster_slurm.yaml ncpus for map_to_reference rule
bwa_threads: 4

#tools used.  need to be module loaded first.  see snakemake file for loads
bwa: /app/software/BWA/0.7.17-foss-2018b/bin/bwa
samtools: /app/software/SAMtools/1.10-GCCcore-8.3.0/bin/samtools
java: /app/software/Java/11.0.2/bin/java
gatk: /app/software/GATK/4.1.4.1-GCCcore-8.3.0-Java-11/gatk
picard_jar: $EBROOTPICARD/picard.jar
